# Generated by Django 4.1.1 on 2022-10-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
    ]
