# Generated by Django 4.1.1 on 2022-09-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=42, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, upload_to='album_covers', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=42, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('src', models.ImageField(upload_to='album_images', verbose_name='Изображение')),
                ('origin_height', models.PositiveIntegerField(blank=True, default=0, verbose_name='Оригинальная высота')),
                ('origin_width', models.PositiveIntegerField(blank=True, default=0, verbose_name='Оригинальная ширина')),
                ('height', models.PositiveIntegerField(blank=True, default=0, verbose_name='Относительная высота')),
                ('width', models.PositiveIntegerField(blank=True, default=0, verbose_name='Относительная ширина')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='gallery.album')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
