# Generated by Django 4.1.1 on 2022-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='src',
            field=models.ImageField(blank=True, upload_to='album_images', verbose_name='Изображение'),
        ),
    ]
